import sulfateFreeShampoo from "../../assets/pro1.WebP";
import antimonyOil from "../../assets/pro2.WebP";
import horsetailSpray from "../../assets/pro3.WebP";
import stylingCream from "../../assets/pro4.WebP";
import naturalHerbalHairBalm from "../../assets/Pro5.webp";
import spirulinaCapsules from "../../assets/pro6.webp";
import indianCostusCapsules from "../../assets/pro7.webp";
import nessFatCream from "../../assets/pro8.webp";

const products = [
  {
    id: 1,
    nameKey: "productsSection.items.horsetailSpray.title",
    image: horsetailSpray,
    categoryKey: "productsSection.categories.hairCare",
    badgeKey: "productsSection.badges.freeSession",
    sessionLink: "#natural-rabbit-hair",
    price: 160,
    oldPrice: 195,
    descriptionKey: "productsSection.items.horsetailSpray.description",
    fullDescriptionKey: "productsSection.items.horsetailSpray.fullDescription",
    howToUseKey: "productsSection.items.horsetailSpray.howToUse",
    volumeKey: "productsSection.items.horsetailSpray.volume",
  },
  {
    id: 2,
    nameKey: "productsSection.items.sulfateFreeShampoo.title",
    image: sulfateFreeShampoo,
    categoryKey: "productsSection.categories.hairCare",
    badgeKey: "productsSection.badges.natural",
    price: 225,
    oldPrice: 270,
    descriptionKey: "productsSection.items.sulfateFreeShampoo.description",
    fullDescriptionKey: "productsSection.items.sulfateFreeShampoo.fullDescription",
    howToUseKey: "productsSection.items.sulfateFreeShampoo.howToUse",
    volumeKey: "productsSection.items.sulfateFreeShampoo.volume",
  },
  {
    id: 3,
    nameKey: "productsSection.items.antimonyOil.title",
    image: antimonyOil,
    categoryKey: "productsSection.categories.naturalOils",
    badgeKey: "productsSection.badges.herbal",
    price: 350,
    oldPrice: 450,
    descriptionKey: "productsSection.items.antimonyOil.description",
    fullDescriptionKey: "productsSection.items.antimonyOil.fullDescription",
    howToUseKey: "productsSection.items.antimonyOil.howToUse",
    volumeKey: "productsSection.items.antimonyOil.volume",
  },
  {
    id: 4,
    nameKey: "productsSection.items.stylingCream.title",
    image: stylingCream,
    categoryKey: "productsSection.categories.hairCare",
    badgeKey: "productsSection.badges.premium",
    price: 195,
    oldPrice: 235,
    descriptionKey: "productsSection.items.stylingCream.description",
    fullDescriptionKey: "productsSection.items.stylingCream.fullDescription",
    howToUseKey: "productsSection.items.stylingCream.howToUse",
    volumeKey: "productsSection.items.stylingCream.volume",
  },
  {
    id: 5,
    nameKey: "productsSection.items.hairBalm.title",
    image: naturalHerbalHairBalm,
    categoryKey: "productsSection.categories.hairCare",
    badgeKey: "productsSection.badges.natural",
    price: 200,
    oldPrice: 250,
    descriptionKey: "productsSection.items.hairBalm.description",
    fullDescriptionKey: "productsSection.items.hairBalm.fullDescription",
    howToUseKey: "productsSection.items.hairBalm.howToUse",
    volumeKey: "productsSection.items.hairBalm.volume",
  },
  {
    id: 6,
    nameKey: "productsSection.items.spirulina.title",
    image: spirulinaCapsules,
    categoryKey: "productsSection.categories.herbalProducts",
    badgeKey: "productsSection.badges.organic",
    price: 350,
    oldPrice: 420,
    descriptionKey: "productsSection.items.spirulina.description",
    fullDescriptionKey: "productsSection.items.spirulina.fullDescription",
    howToUseKey: "productsSection.items.spirulina.howToUse",
    volumeKey: "productsSection.items.spirulina.volume",
  },
  {
    id: 7,
    nameKey: "productsSection.items.indianCostus.title",
    image: indianCostusCapsules,
    categoryKey: "productsSection.categories.herbalProducts",
    badgeKey: "productsSection.badges.natural",
    price: 350,
    oldPrice: 420,
    descriptionKey: "productsSection.items.indianCostus.description",
    fullDescriptionKey: "productsSection.items.indianCostus.fullDescription",
    howToUseKey: "productsSection.items.indianCostus.howToUse",
    volumeKey: "productsSection.items.indianCostus.volume",
  },
  {
    id: 8,
    nameKey: "productsSection.items.herbalCream.title",
    image: nessFatCream,
    categoryKey: "productsSection.categories.bodyCare",
    badgeKey: "productsSection.badges.bestSeller",
    price: 420,
    oldPrice: 480,
    descriptionKey: "productsSection.items.herbalCream.description",
    fullDescriptionKey: "productsSection.items.herbalCream.fullDescription",
    howToUseKey: "productsSection.items.herbalCream.howToUse",
    volumeKey: "productsSection.items.herbalCream.volume",
  },
];

export default products;