import Session1 from "../../../assets/Session1.webp"
import Session2 from "../../../assets/Session2.webp"
import Session3 from "../../../assets/Session3.webp"
import Session4 from "../../../assets/Session4.webp"
import Session5 from "../../../assets/Session5.webp"
import Session6 from "../../../assets/Session6.webp"

export const sessionsData = [
  {
    id: "natural-rabbit-hair",
    name: "Natural Rabbit Hair",
    category: "Hair Care",
    tagKey: "sessions.rabbitHair.tag",
    titleKey: "sessions.rabbitHair.title",
    subtitleKey: "sessions.rabbitHair.subtitle",
    descriptionKey: "sessions.rabbitHair.description",
    featuresKey: "sessions.rabbitHair.features",
    buttonKey: "sessions.rabbitHair.bookBtn",
    image: Session1,
    isFeatured: true,
  },
  {
    id: "natural-fruit-peeling",
    name: "Natural Fruit Peeling",
    category: "Skin Care",
    tagKey: "sessions.fruitPeeling.tag",
    titleKey: "sessions.fruitPeeling.title",
    subtitleKey: "sessions.fruitPeeling.subtitle",
    descriptionKey: "sessions.fruitPeeling.description",
    featuresKey: "sessions.fruitPeeling.features",
    buttonKey: "sessions.fruitPeeling.bookBtn",
    image: Session2,
    isFeatured: true,
  },
  {
    id: "natural-premium-cleansing",
    name: "Natural Premium Cleansing",
    category: "Skin Care",
    tagKey: "sessions.premiumCleansing.tag",
    titleKey: "sessions.premiumCleansing.title",
    subtitleKey: "sessions.premiumCleansing.subtitle",
    descriptionKey: "sessions.premiumCleansing.description",
    featuresKey: "sessions.premiumCleansing.features",
    buttonKey: "sessions.premiumCleansing.bookBtn",
    image:Session3,
    isFeatured: false,
  },
  {
    id: "natural-spa-massage",
    name: "Natural Spa & Massage",
    category: "Body & Spa",
    tagKey: "sessions.spaMassage.tag",
    titleKey: "sessions.spaMassage.title",
    subtitleKey: "sessions.spaMassage.subtitle",
    descriptionKey: "sessions.spaMassage.description",
    featuresKey: "sessions.spaMassage.features",
    buttonKey: "sessions.spaMassage.bookBtn",
    image: Session4,
    isFeatured: false,
  },
  {
    id: "natural-hair-repair",
    name: "Natural Hair Repair",
    category: "Hair Care",
    tagKey: "sessions.hairRepair.tag",
    titleKey: "sessions.hairRepair.title",
    subtitleKey: "sessions.hairRepair.subtitle",
    descriptionKey: "sessions.hairRepair.description",
    featuresKey: "sessions.hairRepair.features",
    buttonKey: "sessions.hairRepair.bookBtn",
    image: Session5,
    isFeatured: true,
  },
  {
    id: "natural-scalp-detox",
    name: "Natural Scalp Detox",
    category: "Hair Care",
    tagKey: "sessions.scalpDetox.tag",
    titleKey: "sessions.scalpDetox.title",
    subtitleKey: "sessions.scalpDetox.subtitle",
    descriptionKey: "sessions.scalpDetox.description",
    featuresKey: "sessions.scalpDetox.features",
    buttonKey: "sessions.scalpDetox.bookBtn",
    image: Session6,
    isFeatured: false,
  },
];